runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
 
- url: /images
  static_dir: images

- url: /set_info
  static_dir: set_info

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on
